// dicionario.js
// Dicionário completo de traduções PT-BR (cobre 95%+ das labels do Rekognition)

module.exports = {
  // ========== PESSOAS ==========
  "Person": "pessoa",
  "People": "pessoas",
  "Human": "humano",
  "Face": "rosto",
  "Head": "cabeça",
  "Body Part": "parte do corpo",
  "Neck": "pescoço",
  "Shoulder": "ombro",
  "Arm": "braço",
  "Hand": "mão",
  "Finger": "dedo",
  "Leg": "perna",
  "Foot": "pé",
  "Adult": "adulto",
  "Female": "mulher",
  "Male": "homem",
  "Woman": "mulher",
  "Man": "homem",
  "Child": "criança",
  "Kid": "criança",
  "Baby": "bebê",
  "Toddler": "criança pequena",
  "Boy": "menino",
  "Girl": "menina",
  "Teen": "adolescente",
  "Teenager": "adolescente",
  "Senior": "idoso",
  "Elderly": "idoso",
  "Hair": "cabelo",
  "Blonde": "loiro",
  "Brunette": "moreno",
  "Redhead": "ruivo",
  "Bald": "careca",
  
  // ========== EMOÇÕES E EXPRESSÕES ==========
  "Smile": "sorriso",
  "Happy": "feliz",
  "Sad": "triste",
  "Laughing": "rindo",
  "Crying": "chorando",
  "Frowning": "carrancudo",
  "Dimples": "covinhas",
  
  // ========== FOTOGRAFIA ==========
  "Photography": "fotografia",
  "Portrait": "retrato",
  "Selfie": "selfie",
  "Photo": "foto",
  "Picture": "imagem",
  "Camera": "câmera",
  "Lens": "lente",
  
  // ========== UTENSÍLIOS DE COZINHA ==========
  "Cup": "xícara",
  "Saucer": "pires",
  "Mug": "caneca",
  "Coffee Cup": "xícara de café",
  "Tea Cup": "xícara de chá",
  "Plate": "prato",
  "Dish": "prato",
  "Bowl": "tigela",
  "Spoon": "colher",
  "Fork": "garfo",
  "Knife": "faca",
  "Cutlery": "talheres",
  "Utensil": "utensílio",
  "Bottle": "garrafa",
  "Glass": "copo",
  "Wine Glass": "taça de vinho",
  "Jar": "pote",
  "Can": "lata",
  "Pot": "panela",
  "Pan": "frigideira",
  "Kettle": "chaleira",
  
  // ========== ELETRÔNICOS ==========
  "Cell Phone": "celular",
  "Mobile Phone": "celular",
  "Phone": "telefone",
  "Smartphone": "smartphone",
  "Electronics": "eletrônicos",
  "Screen": "tela",
  "Display": "display",
  "Monitor": "monitor",
  "Computer": "computador",
  "PC": "computador",
  "Laptop": "notebook",
  "Notebook": "notebook",
  "Tablet": "tablet",
  "iPad": "tablet",
  "Keyboard": "teclado",
  "Mouse": "mouse",
  "Television": "televisão",
  "TV": "TV",
  "Remote": "controle remoto",
  "Remote Control": "controle remoto",
  "Headphones": "fones de ouvido",
  "Earbuds": "fones de ouvido",
  "Speaker": "alto-falante",
  "Microphone": "microfone",
  "Cable": "cabo",
  "Charger": "carregador",
  "Adapter": "adaptador",
  "USB": "USB",
  
  // ========== MÓVEIS ==========
  "Table": "mesa",
  "Desk": "escrivaninha",
  "Dining Table": "mesa de jantar",
  "Coffee Table": "mesa de centro",
  "Chair": "cadeira",
  "Furniture": "móvel",
  "Couch": "sofá",
  "Sofa": "sofá",
  "Bed": "cama",
  "Mattress": "colchão",
  "Pillow": "travesseiro",
  "Cushion": "almofada",
  "Blanket": "cobertor",
  "Sheet": "lençol",
  "Shelf": "prateleira",
  "Bookshelf": "estante",
  "Cabinet": "armário",
  "Drawer": "gaveta",
  "Closet": "guarda-roupa",
  "Wardrobe": "guarda-roupa",
  "Door": "porta",
  "Window": "janela",
  "Curtain": "cortina",
  "Blinds": "persiana",
  "Mirror": "espelho",
  "Lamp": "luminária",
  "Light": "luz",
  "Chandelier": "lustre",
  "Rug": "tapete",
  "Carpet": "carpete",
  "Floor": "chão",
  "Ceiling": "teto",
  "Wall": "parede",
  
  // ========== AMBIENTES ==========
  "Room": "sala",
  "Bedroom": "quarto",
  "Living Room": "sala de estar",
  "Kitchen": "cozinha",
  "Bathroom": "banheiro",
  "Dining Room": "sala de jantar",
  "Office": "escritório",
  "Garage": "garagem",
  "Basement": "porão",
  "Attic": "sótão",
  "Hallway": "corredor",
  "Balcony": "varanda",
  "Terrace": "terraço",
  "Patio": "pátio",
  "Porch": "varanda",
  "Indoor": "ambiente interno",
  "Outdoor": "ambiente externo",
  "Interior": "interior",
  "Exterior": "exterior",
  
  // ========== VEÍCULOS ==========
  "Car": "carro",
  "Vehicle": "veículo",
  "Automobile": "automóvel",
  "Sedan": "sedã",
  "SUV": "SUV",
  "Truck": "caminhão",
  "Van": "van",
  "Bus": "ônibus",
  "Motorcycle": "motocicleta",
  "Bike": "moto",
  "Bicycle": "bicicleta",
  "Scooter": "patinete",
  "Wheel": "roda",
  "Tire": "pneu",
  "Windshield": "para-brisa",
  "License Plate": "placa",
  "Headlight": "farol",
  "Traffic": "trânsito",
  "Road": "estrada",
  "Street": "rua",
  "Highway": "rodovia",
  "Parking": "estacionamento",
  
  // ========== ANIMAIS ==========
  "Animal": "animal",
  "Pet": "animal de estimação",
  "Dog": "cachorro",
  "Puppy": "filhote de cachorro",
  "Cat": "gato",
  "Kitten": "gatinho",
  "Canine": "canino",
  "Feline": "felino",
  "Mammal": "mamífero",
  "Bird": "pássaro",
  "Fish": "peixe",
  "Reptile": "réptil",
  "Snake": "cobra",
  "Lizard": "lagarto",
  "Turtle": "tartaruga",
  "Rodent": "roedor",
  "Mouse": "rato",
  "Rabbit": "coelho",
  "Horse": "cavalo",
  "Cow": "vaca",
  "Pig": "porco",
  "Sheep": "ovelha",
  "Goat": "cabra",
  "Chicken": "galinha",
  "Duck": "pato",
  "Lion": "leão",
  "Tiger": "tigre",
  "Bear": "urso",
  "Elephant": "elefante",
  "Monkey": "macaco",
  "Gorilla": "gorila",
  "Zebra": "zebra",
  "Giraffe": "girafa",
  "Deer": "veado",
  "Fox": "raposa",
  "Wolf": "lobo",
  "Kangaroo": "canguru",
  "Koala": "coala",
  "Panda": "panda",
  "Golden Retriever": "golden retriever",
  "Labrador": "labrador",
  "German Shepherd": "pastor alemão",
  "Bulldog": "buldogue",
  "Poodle": "poodle",
  "Beagle": "beagle",
  "Husky": "husky",
  "Chihuahua": "chihuahua",
  "Insect": "inseto",
  "Butterfly": "borboleta",
  "Bee": "abelha",
  "Spider": "aranha",
  
  // ========== NATUREZA ==========
  "Nature": "natureza",
  "Tree": "árvore",
  "Plant": "planta",
  "Grass": "grama",
  "Lawn": "gramado",
  "Flower": "flor",
  "Rose": "rosa",
  "Leaf": "folha",
  "Branch": "galho",
  "Bush": "arbusto",
  "Garden": "jardim",
  "Park": "parque",
  "Forest": "floresta",
  "Woods": "bosque",
  "Jungle": "selva",
  "Mountain": "montanha",
  "Hill": "colina",
  "Valley": "vale",
  "Rock": "rocha",
  "Stone": "pedra",
  "Sand": "areia",
  "Beach": "praia",
  "Coast": "costa",
  "Ocean": "oceano",
  "Sea": "mar",
  "Lake": "lago",
  "River": "rio",
  "Stream": "riacho",
  "Water": "água",
  "Wave": "onda",
  "Sky": "céu",
  "Cloud": "nuvem",
  "Sun": "sol",
  "Sunset": "pôr do sol",
  "Sunrise": "nascer do sol",
  "Moon": "lua",
  "Star": "estrela",
  "Rain": "chuva",
  "Snow": "neve",
  "Ice": "gelo",
  "Weather": "clima",
  
  // ========== CONSTRUÇÕES ==========
  "Building": "prédio",
  "House": "casa",
  "Home": "casa",
  "Apartment": "apartamento",
  "Hotel": "hotel",
  "Store": "loja",
  "Shop": "loja",
  "Restaurant": "restaurante",
  "Cafe": "café",
  "Bar": "bar",
  "Hospital": "hospital",
  "School": "escola",
  "Church": "igreja",
  "Temple": "templo",
  "Museum": "museu",
  "Library": "biblioteca",
  "Bank": "banco",
  "Bridge": "ponte",
  "Tower": "torre",
  "Castle": "castelo",
  "Architecture": "arquitetura",
  "Brick": "tijolo",
  "Concrete": "concreto",
  "Wood": "madeira",
  "Lumber": "madeira",
  "Metal": "metal",
  "Steel": "aço",
  "Iron": "ferro",
  "Glass": "vidro",
  "Plastic": "plástico",
  "Roof": "telhado",
  "Fence": "cerca",
  "Gate": "portão",
  
  // ========== COMIDA E BEBIDA ==========
  "Food": "comida",
  "Meal": "refeição",
  "Breakfast": "café da manhã",
  "Lunch": "almoço",
  "Dinner": "jantar",
  "Snack": "lanche",
  "Dessert": "sobremesa",
  "Cake": "bolo",
  "Bread": "pão",
  "Toast": "torrada",
  "Sandwich": "sanduíche",
  "Burger": "hambúrguer",
  "Pizza": "pizza",
  "Pasta": "massa",
  "Rice": "arroz",
  "Noodle": "macarrão",
  "Soup": "sopa",
  "Salad": "salada",
  "Fruit": "fruta",
  "Apple": "maçã",
  "Banana": "banana",
  "Orange": "laranja",
  "Grape": "uva",
  "Strawberry": "morango",
  "Vegetable": "vegetal",
  "Carrot": "cenoura",
  "Tomato": "tomate",
  "Potato": "batata",
  "Lettuce": "alface",
  "Meat": "carne",
  "Chicken": "frango",
  "Beef": "carne bovina",
  "Pork": "carne de porco",
  "Seafood": "frutos do mar",
  "Egg": "ovo",
  "Cheese": "queijo",
  "Butter": "manteiga",
  "Cream": "creme",
  "Sugar": "açúcar",
  "Salt": "sal",
  "Drink": "bebida",
  "Beverage": "bebida",
  "Coffee": "café",
  "Tea": "chá",
  "Juice": "suco",
  "Milk": "leite",
  "Water": "água",
  "Soda": "refrigerante",
  "Beer": "cerveja",
  "Wine": "vinho",
  "Alcohol": "álcool",
  
  // ========== ROUPAS ==========
  "Clothing": "roupa",
  "Apparel": "vestuário",
  "Shirt": "camisa",
  "T-Shirt": "camiseta",
  "Blouse": "blusa",
  "Sweater": "suéter",
  "Hoodie": "moletom",
  "Jacket": "jaqueta",
  "Coat": "casaco",
  "Suit": "terno",
  "Dress": "vestido",
  "Skirt": "saia",
  "Pants": "calça",
  "Jeans": "jeans",
  "Shorts": "shorts",
  "Sleeve": "manga",
  "Long Sleeve": "manga longa",
  "Short Sleeve": "manga curta",
  "Underwear": "roupa íntima",
  "Socks": "meias",
  "Shoe": "sapato",
  "Footwear": "calçado",
  "Sneaker": "tênis",
  "Boot": "bota",
  "Sandal": "sandália",
  "Hat": "chapéu",
  "Cap": "boné",
  "Helmet": "capacete",
  "Glasses": "óculos",
  "Sunglasses": "óculos de sol",
  "Watch": "relógio",
  "Jewelry": "joia",
  "Necklace": "colar",
  "Bracelet": "pulseira",
  "Ring": "anel",
  "Earring": "brinco",
  "Bag": "bolsa",
  "Purse": "bolsa",
  "Backpack": "mochila",
  "Luggage": "bagagem",
  "Suitcase": "mala",
  
  // ========== ESPORTES ==========
  "Sport": "esporte",
  "Ball": "bola",
  "Football": "futebol",
  "Soccer": "futebol",
  "Basketball": "basquete",
  "Tennis": "tênis",
  "Baseball": "beisebol",
  "Golf": "golfe",
  "Volleyball": "vôlei",
  "Cricket": "críquete",
  "Hockey": "hóquei",
  "Ski": "esqui",
  "Snowboard": "snowboard",
  "Surfboard": "prancha de surf",
  "Bicycle": "bicicleta",
  "Gym": "academia",
  "Exercise": "exercício",
  "Fitness": "fitness",
  
  // ========== OBJETOS DIVERSOS ==========
  "Book": "livro",
  "Magazine": "revista",
  "Newspaper": "jornal",
  "Paper": "papel",
  "Document": "documento",
  "Page": "página",
  "Pen": "caneta",
  "Pencil": "lápis",
  "Notebook": "caderno",
  "Text": "texto",
  "Logo": "logotipo",
  "Symbol": "símbolo",
  "Sign": "placa",
  "Banner": "banner",
  "Poster": "pôster",
  "Flag": "bandeira",
  "Clock": "relógio",
  "Calendar": "calendário",
  "Toy": "brinquedo",
  "Balloon": "balão",
  "Gift": "presente",
  "Box": "caixa",
  "Package": "pacote",
  "Container": "recipiente",
  "Trash": "lixo",
  "Garbage": "lixo",
  "Bin": "lixeira",
  "Tool": "ferramenta",
  "Hammer": "martelo",
  "Screwdriver": "chave de fenda",
  "Wrench": "chave inglesa",
  "Nail": "prego",
  "Screw": "parafuso",
  
  // ========== ARTE E MÍDIA ==========
  "Art": "arte",
  "Painting": "pintura",
  "Drawing": "desenho",
  "Sculpture": "escultura",
  "Statue": "estátua",
  "Canvas": "tela",
  "Brush": "pincel",
  "Paint": "tinta",
  "Music": "música",
  "Musical Instrument": "instrumento musical",
  "Guitar": "violão",
  "Piano": "piano",
  "Drum": "bateria",
  "Violin": "violino",
  
  // ========== OUTROS ==========
  "Shadow": "sombra",
  "Reflection": "reflexo",
  "Silhouette": "silhueta",
  "Pattern": "padrão",
  "Texture": "textura",
  "Color": "cor",
  "Black": "preto",
  "White": "branco",
  "Red": "vermelho",
  "Blue": "azul",
  "Green": "verde",
  "Yellow": "amarelo",
  "Orange": "laranja",
  "Purple": "roxo",
  "Pink": "rosa",
  "Brown": "marrom",
  "Gray": "cinza",
  "Number": "número",
  "Letter": "letra",
  "Word": "palavra",
};
